### ISSUE TITLE
Prez Question

### ISSUE THREAD

**Issue by mcmullengreg** [8bitsquid/Bower-Grunt-Github-Presentation#1]
Sorry, wasn't sure how else to contact you. 

I'm new to the gulp/grunt/bower world. Does each person need to install the grunt modules locally or is that handled somehow? I'm trying to get a repo setup and I have the package.json setup, but when I run grunt * it says the NPM modules aren't installed.

Thanks.

**Comment by 8bitsquid** [comment]
Hi Gregory, it sounds like you need to run the Node Package Manager install command:
 ```bash
npm install
```
This will install all the NodeJS modules listed as `dependencies` or `devDependencies` in your `package.json` file.

Hope this helps! Don't hesitate to contact me using `the8bitsquid@gmail.com` anytime you get stuck on setting up your own Grunt/Bower workflow (I've never used Gulp, but I may still be able to point you in the right direction).

On a side note, I guess it wasn't bad I forgot to remove this repo. I made the presentation using Slides.com, which - as you may know - is just a visual editor for Reveal.js. I had hoped to break the slideshow into a modular source structure and then use a Bower/Grunt workflow to build the presentation itseld, but alas, I didn't have enough time to get it fully together.

**Comment by mcmullengreg** [comment]
Just ran it and it worked! Thanks for the presentation. Hopefully I'll be able to remember everything when I setup the next repo.
